services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  readings:
    image: ghcr.io/shekelator/ruachreadings:main
    ports:
      - "8080"
  homepage-of-dave:
    image: ghcr.io/shekelator/homepage-of-dave:master
    environment:
      - SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
      - SPACES_SECRET=${SPACES_SECRET}
    # image: homepage-of-dave:master
    ports:
      - "5000"
